### PR TITLE
WIP: add german tanslation

### PR DESCRIPTION
**Pull request by Danfro**
This MR will add the German translation file to the project. 

What is missing:
- add German to language selection
- test on device

I am lost with QtCreator since I never used that. But I wanted to push the translation file now because that is ready in this state for several weeks now. I am just lacking the time to read through your instructions and tinker around with QtCreator to get the app build for UT.

### CODE REVIEW

**Comment by mateosalta** [comment]
ah, I always used clickable to generate the binary - then put inside a kind of click package and run again

**Comment by mateosalta** [comment]
we will want a version of this translated:

file will be App/assets/sprites/charging_paper/charging_paper_L.de.png

charging_paper_L en

**Comment by Danfro** [comment]
Hmm. I am using clickable generally too. Does Dead Ascend building work with clickable? I only remember lots of errors when I tried.

--

**Comment by Danfro** [comment]
You are right. Does that mean editing the image? Or does it have a kind of overlay? Need to have a look later...

--

**Comment by mateosalta** [comment]
yep, straight gimp'n on top of the image

**Comment by mateosalta** [comment]
but if you get me what it needs to say, I could try my hand at the manipulation of the picture

**Comment by mateosalta** [comment]
there might be bugs in how translation ? not sure, some fields work, others didnt - maybe I need to run the script to get translatable fields?

**Comment by Danfro** [comment]
Hmm. In translations folder there is an [Extra.qml](https://github.com/mateosalta/DeadAscend/blob/ut/App/translations/Extra.qml) file. There is a comment, that this file was auto-generated by [translation.py](https://github.com/mateosalta/DeadAscend/blob/ut/sbin/translation.py). But if I try to run it with `python3 sbin/translation.py`, it complains about needing a scene file. If I then try `python3 sbin/translation.py scenes/scenes.tmx` I get some more errors about some JSONDecodeError.

This might be a trace. But I may not solve this today.

**Comment by Danfro** [comment]
Why the heck are there all those `<translation type="unfinished">Suche einen Weg um die Klappe offen zu halten.</translation>` type="unfinished" markers there? I am sure I deleted them all. Also in other places there are "obsolete" markers. Something must have happened before I pushed and I did not double check.

That might be why the strings don't show up in the game.

**Comment by Danfro** [comment]
I definitely need to amend some translated strings... :thinking:

**Comment by mateosalta** [comment]
oh do the "unfinished" ones not show? 

It looks like when i ran some commands more of the strings were brought in

**Comment by Danfro** [comment]
It was only a guess that the "unfinished" label might be the source.

I discovered how to use [translation.py](https://github.com/mateosalta/DeadAscend/blob/master/sbin/translation.py) :  we need to run the following command in the main folder:
`python3 sbin/translation.py App/assets/scenes/scenes.json`

This will autogenerate the [Extras.qml](https://github.com/mateosalta/DeadAscend/blob/master/App/translations/Extra.qml). I can add a note to the python file for this.

This does extract strings from [scenes.json](https://github.com/mateosalta/DeadAscend/blob/master/App/assets/scenes/scenes.json). Those strings specified in that file seem to be the ones that come up translated.

Ah, just found it: [translation.md](https://github.com/mateosalta/DeadAscend/blob/master/docs/Translations.md) this file holds the instructions. For some reason, when running the last command ' lrelease translations/*.ts`, I encounter an error, that lrelease can not be found. I guess something on my end. :thinking:

**Comment by Danfro** [comment]
Ok, looks like I do not have Qt5 installed locally. Thankfully there is `clickable ide qtcreator`. I got that running now and updated the strings. Need to build the app and test.

**Pull request merged**
